---
- name: Web Playbook
  become: true
  hosts: dev_web
  
  tasks:
   - name: Install Docker
     yum:
      name: docker
      state: present

   - name: Starting Docker
     service:
      name: docker
      state: started

   - name: Install docker-compose
     shell: |
      sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose

   - name: Install Git 
     yum: 
      name: git 
      state: present

   - name: Git cloning stock-price-app dir
     git:
      repo: https://github.com/techbleat/stock-price-app.git
      dest: stock-price-app
